# GENERATED FILE. Use with Kubernetes 1.7+
# TO UPDATE, modify files in install/kubernetes/templates and run install/updateVersion.sh
################################
# Istio initializer
################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-inject
  namespace: istio-system
data:
  config: |-
    policy: "enabled"
    namespaces: [""] # everything, aka v1.NamepsaceAll, aka cluster-wide
    initializerName: "sidecar.initializer.istio.io"
    params:
      initImage: gcr.io/istio-testing/proxy_init:3101ea9d82a5f83b699c2d3245b371a19fa6bef4
      proxyImage: gcr.io/istio-testing/proxy_debug:3101ea9d82a5f83b699c2d3245b371a19fa6bef4
      verbosity: 2
      version: 3101ea9d82a5f83b699c2d3245b371a19fa6bef4
      meshConfigMapName: istio
      imagePullPolicy: IfNotPresent
      debugMode: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-initializer-service-account
  namespace: istio-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: istio-initializer
  namespace: istio-system
  annotations:
    sidecar.istio.io/inject: "false"
  initializers:
    pending: []
  labels:
    istio: istio-initializer
spec:
  replicas: 1
  template:
    metadata:
      name: istio-initializer
      labels:
        istio: initializer
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-initializer-service-account
      containers:
        - name: initializer
          image: gcr.io/istio-testing/sidecar_initializer:3101ea9d82a5f83b699c2d3245b371a19fa6bef4
          imagePullPolicy: IfNotPresent
          args:
            - --port=8083
            - --namespace=istio-system
            - -v=2
          volumeMounts:
          - name: config-volume
            mountPath: /etc/istio/config
      volumes:
      - name: config-volume
        configMap:
          name: istio
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: istio-sidecar
initializers:
  - name: sidecar.initializer.istio.io
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - deployments
          - statefulsets
          - jobs
          - daemonsets
---
